name: GenesisSMP
main: eu.genesismc.genesissmp.GenesisSMP
version: 2.2
author: CW_UK
api-version: 1.16
depend: [LuckPerms, Essentials, WorldGuard, WorldEdit, UltraPunishments]
softdepend: [EnjinMinecraftPlugin]

commands:
  prefix:
    description: Sets a prefix
    default: true
  suffix:
    description: Sets a suffix
    default: true
  gsmp:
    description: Admin command for GenesisSMP
    default: op
  clearcrate:
    description: Clears the loot crate in The End
    default: op
    usage: /clearcrate <now|later>
    permission: clearcrate.admin
    permission-message: You do not have permission to perform this command.
  invman:
    description: Manages saving/loading of inventories between GMS and GMC.
    usage: /invman <save|restore> <username>
    default: op
  plot:
    description: Manages creative plot access.
    usage: /plot <enter|leave|lock|unlock> [number]
    default: op

permissions:
  genesisprefix.*:
    description: Gives access to all prefix commands
    children:
      genesisprefix.setothers: true
      genesisprefix.removeothers: true
      genesisprefix.code.k: true
      genesisprefix.code.l: true
      genesisprefix.code.o: true
      genesisprefix.code.m: true
      genesisprefix.code.n: true
      genesisprefix.donator.prefix: true
      genesisprefix.donator.suffix: true
  genesisprefix.setothers:
    description: Gives a user access to set prefixes/suffixes for other players.
    default: op
  genesisprefix.removeothers:
    description: Gives a user access to remove prefixes/suffixes of other players.
    default: op
  genesisprefix.code.k:
    default: op
    description: Allows using magic (scramble) formatting code.
  genesisprefix.code.l:
    default: true
    description: Allows using bold formatting code.
  genesisprefix.code.o:
    default: true
    description: Allows using italic formatting code.
  genesisprefix.code.m:
    default: true
    description: Allows using strikethrough formatting code.
  genesisprefix.code.n:
    default: true
    description: Allows using underline formatting code.
  genesisprefix.donator.prefix:
    default: op
    description: Given to players who have purhcased a prefix token.
  genesisprefix.donator.suffix:
    default: op
    description: Given to players who have purchased a suffix token.

  genesissmp.plots.lock:
    default: op
    description: Allows locking of plot/plots to prevent users accessing.

  genesissmp.blocklimit.bypass.all:
    default: op
    description: Allows bypassing of block place limits.
